-- BANKGUARD AI – Schema Validation
-- Verifies all five BANKGUARD schemas exist in USER$STRATEGYSAMUEL.

SELECT SCHEMA_NAME,
       COMMENT,
       CREATED
  FROM USER$STRATEGYSAMUEL.INFORMATION_SCHEMA.SCHEMATA
 WHERE SCHEMA_NAME LIKE 'BANKGUARD_%'
 ORDER BY SCHEMA_NAME;
