-- BANKGUARD AI – M1 Core Views
-- Schema: BANKGUARD_CORE
-- Idempotent: uses CREATE OR REPLACE VIEW

USE DATABASE BANKGUARD_DB;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- V_CUSTOMER_360 – Unified customer view with aggregated metrics
-- ============================================================
CREATE OR REPLACE VIEW BANKGUARD_CORE.V_CUSTOMER_360 AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_TYPE,
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_RISK_RATING,
    c.KYC_STATUS,
    c.CUSTOMER_SINCE,
    c.ANNUAL_INCOME,
    c.COUNTRY,
    c.CITY,
    acct.ACCOUNT_COUNT,
    acct.TOTAL_BALANCE,
    ben.BENEFICIARY_COUNT,
    txn.TRANSACTION_COUNT,
    txn.TOTAL_DEBITS,
    txn.TOTAL_CREDITS,
    txn.FIRST_TRANSACTION_DATE,
    txn.LAST_TRANSACTION_DATE,
    alrt.ALERT_COUNT,
    alrt.OPEN_ALERT_COUNT,
    inv.CASE_COUNT,
    inv.OPEN_CASE_COUNT
FROM BANKGUARD_RAW.CUSTOMERS c
LEFT JOIN (
    SELECT CUSTOMER_ID,
           COUNT(*) AS ACCOUNT_COUNT,
           SUM(BALANCE) AS TOTAL_BALANCE
    FROM BANKGUARD_RAW.ACCOUNTS
    GROUP BY CUSTOMER_ID
) acct ON c.CUSTOMER_ID = acct.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS BENEFICIARY_COUNT
    FROM BANKGUARD_RAW.BENEFICIARIES
    GROUP BY CUSTOMER_ID
) ben ON c.CUSTOMER_ID = ben.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID,
           COUNT(*) AS TRANSACTION_COUNT,
           SUM(CASE WHEN TRANSACTION_TYPE != 'SALARY_CREDIT' THEN AMOUNT ELSE 0 END) AS TOTAL_DEBITS,
           SUM(CASE WHEN TRANSACTION_TYPE = 'SALARY_CREDIT' THEN AMOUNT ELSE 0 END) AS TOTAL_CREDITS,
           MIN(TRANSACTION_DATE) AS FIRST_TRANSACTION_DATE,
           MAX(TRANSACTION_DATE) AS LAST_TRANSACTION_DATE
    FROM BANKGUARD_RAW.TRANSACTIONS
    GROUP BY CUSTOMER_ID
) txn ON c.CUSTOMER_ID = txn.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID,
           COUNT(*) AS ALERT_COUNT,
           SUM(CASE WHEN STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_ALERT_COUNT
    FROM BANKGUARD_RAW.FRAUD_ALERTS
    GROUP BY CUSTOMER_ID
) alrt ON c.CUSTOMER_ID = alrt.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID,
           COUNT(*) AS CASE_COUNT,
           SUM(CASE WHEN CASE_STATUS IN ('OPEN','IN_PROGRESS','ESCALATED') THEN 1 ELSE 0 END) AS OPEN_CASE_COUNT
    FROM BANKGUARD_RAW.INVESTIGATION_CASES
    GROUP BY CUSTOMER_ID
) inv ON c.CUSTOMER_ID = inv.CUSTOMER_ID;

-- ============================================================
-- V_TRANSACTION_ENRICHED – Transactions with customer/account context
-- ============================================================
CREATE OR REPLACE VIEW BANKGUARD_CORE.V_TRANSACTION_ENRICHED AS
SELECT
    t.TRANSACTION_ID,
    t.ACCOUNT_ID,
    t.CUSTOMER_ID,
    c.CUSTOMER_TYPE,
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_RISK_RATING,
    c.CITY AS CUSTOMER_CITY,
    a.ACCOUNT_TYPE,
    a.ACCOUNT_STATUS,
    t.TRANSACTION_DATE,
    t.TRANSACTION_TYPE,
    t.AMOUNT,
    t.CURRENCY,
    t.CHANNEL,
    t.MERCHANT,
    t.BENEFICIARY_ID,
    b.COUNTRY AS BENEFICIARY_COUNTRY,
    b.BANK_NAME AS BENEFICIARY_BANK,
    t.COUNTRY AS TRANSACTION_COUNTRY,
    t.DEVICE_ID,
    t.IP_ADDRESS,
    t.TRANSACTION_STATUS,
    CASE WHEN t.TRANSACTION_TYPE = 'SALARY_CREDIT' THEN 'CREDIT' ELSE 'DEBIT' END AS DIRECTION,
    CASE WHEN t.COUNTRY != 'India' THEN TRUE ELSE FALSE END AS IS_INTERNATIONAL
FROM BANKGUARD_RAW.TRANSACTIONS t
JOIN BANKGUARD_RAW.CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
JOIN BANKGUARD_RAW.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN BANKGUARD_RAW.BENEFICIARIES b ON t.BENEFICIARY_ID = b.BENEFICIARY_ID;
