-- BANKGUARD AI – M1 Table DDL
-- Database: BANKGUARD_DB
-- Schema: BANKGUARD_RAW
-- Idempotent: uses CREATE OR REPLACE

USE DATABASE BANKGUARD_DB;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- CUSTOMERS
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.CUSTOMERS (
    CUSTOMER_ID        VARCHAR(20)    NOT NULL,
    CUSTOMER_TYPE      VARCHAR(20)    NOT NULL  COMMENT 'INDIVIDUAL or BUSINESS',
    CUSTOMER_SEGMENT   VARCHAR(20)    NOT NULL  COMMENT 'RETAIL, AFFLUENT, SME, CORPORATE',
    CUSTOMER_RISK_RATING VARCHAR(10)  NOT NULL  COMMENT 'LOW, MEDIUM, HIGH',
    KYC_STATUS         VARCHAR(20)    NOT NULL  COMMENT 'VERIFIED, PENDING, EXPIRED',
    CUSTOMER_SINCE     DATE           NOT NULL,
    ANNUAL_INCOME      NUMBER(18,2)   NOT NULL,
    COUNTRY            VARCHAR(50)    NOT NULL,
    CITY               VARCHAR(50)    NOT NULL,
    CREATED_AT         TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
) COMMENT = 'Synthetic customer profiles. All data is fictional.';

-- ============================================================
-- ACCOUNTS
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.ACCOUNTS (
    ACCOUNT_ID        VARCHAR(20)    NOT NULL,
    CUSTOMER_ID       VARCHAR(20)    NOT NULL,
    ACCOUNT_TYPE      VARCHAR(20)    NOT NULL  COMMENT 'SAVINGS, CURRENT, SALARY, FD, LOAN',
    OPEN_DATE         DATE           NOT NULL,
    BALANCE           NUMBER(18,2)   NOT NULL,
    ACCOUNT_STATUS    VARCHAR(20)    NOT NULL  COMMENT 'ACTIVE, DORMANT, CLOSED, FROZEN',
    CURRENCY          VARCHAR(3)     NOT NULL  DEFAULT 'INR',
    CREATED_AT        TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT        TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES BANKGUARD_RAW.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Synthetic bank accounts. All data is fictional.';

-- ============================================================
-- BENEFICIARIES
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.BENEFICIARIES (
    BENEFICIARY_ID     VARCHAR(20)    NOT NULL,
    CUSTOMER_ID        VARCHAR(20)    NOT NULL,
    CREATED_DATE       DATE           NOT NULL,
    COUNTRY            VARCHAR(50)    NOT NULL,
    BANK_NAME          VARCHAR(100)   NOT NULL,
    ACCOUNT_TYPE       VARCHAR(20)    NOT NULL  COMMENT 'SAVINGS, CURRENT, NRE, NRO',
    BENEFICIARY_STATUS VARCHAR(20)    NOT NULL  COMMENT 'ACTIVE, INACTIVE, BLOCKED',
    CREATED_AT         TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_BENEFICIARIES PRIMARY KEY (BENEFICIARY_ID),
    CONSTRAINT FK_BENEFICIARIES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES BANKGUARD_RAW.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Synthetic beneficiary records. All data is fictional.';

-- ============================================================
-- TRANSACTIONS
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.TRANSACTIONS (
    TRANSACTION_ID    VARCHAR(20)    NOT NULL,
    ACCOUNT_ID        VARCHAR(20)    NOT NULL,
    CUSTOMER_ID       VARCHAR(20)    NOT NULL,
    TRANSACTION_DATE  TIMESTAMP_NTZ  NOT NULL,
    TRANSACTION_TYPE  VARCHAR(30)    NOT NULL  COMMENT 'SALARY_CREDIT, ATM_WITHDRAWAL, POS_PURCHASE, UPI_PAYMENT, UTILITY_PAYMENT, RENT_PAYMENT, EMI_PAYMENT, DOMESTIC_TRANSFER, INTERNATIONAL_TRANSFER',
    AMOUNT            NUMBER(18,2)   NOT NULL,
    CURRENCY          VARCHAR(3)     NOT NULL  DEFAULT 'INR',
    CHANNEL           VARCHAR(20)    NOT NULL  COMMENT 'BRANCH, ATM, ONLINE, MOBILE, POS',
    MERCHANT          VARCHAR(100)            COMMENT 'Merchant name for POS/online transactions',
    BENEFICIARY_ID    VARCHAR(20)             COMMENT 'FK to BENEFICIARIES for transfers',
    COUNTRY           VARCHAR(50)    NOT NULL  DEFAULT 'India',
    DEVICE_ID         VARCHAR(50)             COMMENT 'Synthetic device identifier',
    IP_ADDRESS        VARCHAR(45)             COMMENT 'Synthetic IP address',
    TRANSACTION_STATUS VARCHAR(20)   NOT NULL  DEFAULT 'COMPLETED' COMMENT 'COMPLETED, PENDING, FAILED, REVERSED',
    CREATED_AT        TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_TXN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES BANKGUARD_RAW.ACCOUNTS(ACCOUNT_ID),
    CONSTRAINT FK_TXN_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES BANKGUARD_RAW.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Synthetic financial transactions. All data is fictional.';

-- ============================================================
-- FRAUD_ALERTS
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.FRAUD_ALERTS (
    ALERT_ID          VARCHAR(20)    NOT NULL,
    CUSTOMER_ID       VARCHAR(20)    NOT NULL,
    TRANSACTION_ID    VARCHAR(20),
    ALERT_TYPE        VARCHAR(50)    NOT NULL  COMMENT 'VELOCITY_SPIKE, STRUCTURING, GEO_ANOMALY, DORMANT_ACTIVATION, VALUE_SPIKE, CHANNEL_ANOMALY, BENEFICIARY_BURST, NETWORK_PATTERN, COMBINED',
    RISK_SCORE        NUMBER(5,2)    NOT NULL  COMMENT 'Illustrative score 0-100',
    RULE_TRIGGERED    VARCHAR(100)   NOT NULL  COMMENT 'Rule identifier that generated this alert',
    ALERT_DATE        TIMESTAMP_NTZ  NOT NULL,
    STATUS            VARCHAR(30)    NOT NULL  DEFAULT 'OPEN' COMMENT 'OPEN, INVESTIGATING, CLOSED_TRUE_POSITIVE, CLOSED_FALSE_POSITIVE',
    CREATED_AT        TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FRAUD_ALERTS PRIMARY KEY (ALERT_ID),
    CONSTRAINT FK_ALERTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES BANKGUARD_RAW.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Synthetic fraud/AML alerts. All data is fictional.';

-- ============================================================
-- INVESTIGATION_CASES
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.INVESTIGATION_CASES (
    CASE_ID           VARCHAR(20)    NOT NULL,
    ALERT_ID          VARCHAR(20)    NOT NULL,
    CUSTOMER_ID       VARCHAR(20)    NOT NULL,
    CASE_STATUS       VARCHAR(20)    NOT NULL  COMMENT 'OPEN, IN_PROGRESS, ESCALATED, CLOSED',
    CASE_PRIORITY     VARCHAR(10)    NOT NULL  COMMENT 'LOW, MEDIUM, HIGH, CRITICAL',
    ANALYST           VARCHAR(50)             COMMENT 'Assigned analyst (synthetic)',
    OPEN_DATE         DATE           NOT NULL,
    CLOSE_DATE        DATE,
    CLOSURE_REASON    VARCHAR(200),
    CREATED_AT        TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT        TIMESTAMP_NTZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CASES PRIMARY KEY (CASE_ID),
    CONSTRAINT FK_CASES_ALERT FOREIGN KEY (ALERT_ID) REFERENCES BANKGUARD_RAW.FRAUD_ALERTS(ALERT_ID),
    CONSTRAINT FK_CASES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES BANKGUARD_RAW.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Synthetic investigation cases. All data is fictional.';

-- ============================================================
-- SCENARIO_METADATA (ground truth for evaluation)
-- ============================================================
CREATE OR REPLACE TABLE BANKGUARD_RAW.SCENARIO_METADATA (
    SCENARIO_ID        VARCHAR(20)    NOT NULL,
    SCENARIO_TYPE      VARCHAR(50)    NOT NULL  COMMENT 'VELOCITY_SPIKE, STRUCTURING, BENEFICIARY_BURST, GEO_ANOMALY, DORMANT_ACTIVATION, VALUE_SPIKE, CHANNEL_ANOMALY, NETWORK_PATTERN, COMBINED',
    CUSTOMER_ID        VARCHAR(20)    NOT NULL,
    ACCOUNT_ID         VARCHAR(20),
    START_DATE         DATE           NOT NULL,
    END_DATE           DATE           NOT NULL,
    EXPECTED_SIGNALS   VARCHAR(500)   NOT NULL  COMMENT 'Comma-separated list of expected detection signals',
    EXPECTED_RISK_CLASS VARCHAR(20)   NOT NULL  COMMENT 'LOW, MEDIUM, HIGH, CRITICAL',
    DESCRIPTION        VARCHAR(1000)  NOT NULL,
    CONSTRAINT PK_SCENARIO PRIMARY KEY (SCENARIO_ID)
) COMMENT = 'Ground-truth metadata for synthetic risk scenarios. For evaluation/testing only.';
