-- BANKGUARD AI – M1 Seed: Hero Case CUST-1042
-- Deterministic hero customer with combined risk signals.
-- See SCENARIO_METADATA SCN-I for ground truth.
--
-- Narrative:
--   Historical normal monthly outgoing: ~INR 12 lakh
--   Anomalous burst: ~INR 57 lakh in 36 hours
--   5 new beneficiaries (created days before burst)
--   7 transactions: India → UAE → Hong Kong
--   4 structuring transactions (just below INR 10 lakh)
--   Expected M2 risk score: ~94/100 CRITICAL

USE DATABASE BANKGUARD_DB;
USE SCHEMA BANKGUARD_RAW;

-- Hero customer
INSERT INTO CUSTOMERS VALUES (
    'CUST-1042', 'INDIVIDUAL', 'AFFLUENT', 'HIGH', 'VERIFIED',
    DATEADD('year', -3, CURRENT_DATE()), 3600000.00, 'India', 'Mumbai',
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- Hero accounts
INSERT INTO ACCOUNTS VALUES
    ('ACCT-H1042', 'CUST-1042', 'SAVINGS', DATEADD('year', -3, CURRENT_DATE()), 850000.00, 'ACTIVE', 'INR', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('ACCT-H1043', 'CUST-1042', 'CURRENT', DATEADD('year', -2, CURRENT_DATE()), 1250000.00, 'ACTIVE', 'INR', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 5 new beneficiaries (created within last 5 days)
INSERT INTO BENEFICIARIES VALUES
    ('BEN-H1042A', 'CUST-1042', DATEADD('day', -5, CURRENT_DATE()), 'UAE', 'Emirates NBD', 'CURRENT', 'ACTIVE', CURRENT_TIMESTAMP()),
    ('BEN-H1042B', 'CUST-1042', DATEADD('day', -5, CURRENT_DATE()), 'UAE', 'Mashreq Bank', 'CURRENT', 'ACTIVE', CURRENT_TIMESTAMP()),
    ('BEN-H1042C', 'CUST-1042', DATEADD('day', -4, CURRENT_DATE()), 'Hong Kong', 'Bank of China', 'CURRENT', 'ACTIVE', CURRENT_TIMESTAMP()),
    ('BEN-H1042D', 'CUST-1042', DATEADD('day', -4, CURRENT_DATE()), 'Hong Kong', 'HSBC', 'CURRENT', 'ACTIVE', CURRENT_TIMESTAMP()),
    ('BEN-H1042E', 'CUST-1042', DATEADD('day', -3, CURRENT_DATE()), 'India', 'Axis Bank', 'SAVINGS', 'ACTIVE', CURRENT_TIMESTAMP());

-- 11 months of normal history (~INR 12L/month outgoing via ACCT-H1042)
INSERT INTO TRANSACTIONS
WITH months AS (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS m FROM TABLE(GENERATOR(ROWCOUNT => 11))
),
txns_per_month AS (
    SELECT m, s.seq FROM months
    CROSS JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS seq FROM TABLE(GENERATOR(ROWCOUNT => 10))) s
)
SELECT
    'TXN-HR' || LPAD((ROW_NUMBER() OVER (ORDER BY m, seq))::VARCHAR, 5, '0'),
    'ACCT-H1042', 'CUST-1042',
    DATEADD('day', -(m * 30) + seq * 3, CURRENT_DATE())::TIMESTAMP_NTZ + INTERVAL '10 hours',
    CASE MOD(seq, 5)
        WHEN 0 THEN 'SALARY_CREDIT' WHEN 1 THEN 'RENT_PAYMENT' WHEN 2 THEN 'UPI_PAYMENT'
        WHEN 3 THEN 'DOMESTIC_TRANSFER' ELSE 'UTILITY_PAYMENT'
    END,
    CASE MOD(seq, 5)
        WHEN 0 THEN 300000 WHEN 1 THEN 45000 WHEN 2 THEN 5000+MOD(ABS(HASH(m*31+seq)),15000)
        WHEN 3 THEN 40000+MOD(ABS(HASH(m*37+seq)),30000) ELSE 3000+MOD(ABS(HASH(m*41+seq)),7000)
    END,
    'INR',
    CASE MOD(seq, 5) WHEN 0 THEN 'ONLINE' WHEN 2 THEN 'MOBILE' ELSE 'ONLINE' END,
    NULL, NULL, 'India', 'DEV-HR01', '10.50.100.42', 'COMPLETED', CURRENT_TIMESTAMP()
FROM txns_per_month;

-- Anomalous 36-hour burst: 7 transactions totaling INR 57,00,000
-- 4 structuring transactions (INR 9.5L-9.95L, just below INR 10L threshold)
INSERT INTO TRANSACTIONS VALUES
    ('TXN-HERO01', 'ACCT-H1043', 'CUST-1042', DATEADD('hour', -36, CURRENT_TIMESTAMP()),
     'INTERNATIONAL_TRANSFER', 995000.00, 'INR', 'ONLINE', NULL, 'BEN-H1042A', 'UAE', 'DEV-HR02', '10.50.200.99', 'COMPLETED', CURRENT_TIMESTAMP()),
    ('TXN-HERO02', 'ACCT-H1043', 'CUST-1042', DATEADD('hour', -30, CURRENT_TIMESTAMP()),
     'INTERNATIONAL_TRANSFER', 990000.00, 'INR', 'ONLINE', NULL, 'BEN-H1042B', 'UAE', 'DEV-HR02', '10.50.200.99', 'COMPLETED', CURRENT_TIMESTAMP()),
    ('TXN-HERO03', 'ACCT-H1043', 'CUST-1042', DATEADD('hour', -24, CURRENT_TIMESTAMP()),
     'INTERNATIONAL_TRANSFER', 985000.00, 'INR', 'ONLINE', NULL, 'BEN-H1042C', 'Hong Kong', 'DEV-HR03', '10.50.201.15', 'COMPLETED', CURRENT_TIMESTAMP()),
    ('TXN-HERO04', 'ACCT-H1043', 'CUST-1042', DATEADD('hour', -18, CURRENT_TIMESTAMP()),
     'INTERNATIONAL_TRANSFER', 980000.00, 'INR', 'ONLINE', NULL, 'BEN-H1042D', 'Hong Kong', 'DEV-HR03', '10.50.201.15', 'COMPLETED', CURRENT_TIMESTAMP()),
    ('TXN-HERO05', 'ACCT-H1042', 'CUST-1042', DATEADD('hour', -12, CURRENT_TIMESTAMP()),
     'DOMESTIC_TRANSFER', 850000.00, 'INR', 'MOBILE', NULL, 'BEN-H1042E', 'India', 'DEV-HR01', '10.50.100.42', 'COMPLETED', CURRENT_TIMESTAMP()),
    ('TXN-HERO06', 'ACCT-H1043', 'CUST-1042', DATEADD('hour', -6, CURRENT_TIMESTAMP()),
     'INTERNATIONAL_TRANSFER', 500000.00, 'INR', 'ONLINE', NULL, 'BEN-H1042A', 'UAE', 'DEV-HR02', '10.50.200.99', 'COMPLETED', CURRENT_TIMESTAMP()),
    ('TXN-HERO07', 'ACCT-H1042', 'CUST-1042', DATEADD('hour', -2, CURRENT_TIMESTAMP()),
     'DOMESTIC_TRANSFER', 400000.00, 'INR', 'MOBILE', NULL, 'BEN-H1042E', 'India', 'DEV-HR01', '10.50.100.42', 'COMPLETED', CURRENT_TIMESTAMP());

-- Hero alerts
INSERT INTO FRAUD_ALERTS VALUES
    ('ALT-HERO1', 'CUST-1042', 'TXN-HERO01', 'COMBINED', 94.00, 'RULE-COMBINED-001', DATEADD('hour', -36, CURRENT_TIMESTAMP()), 'OPEN', CURRENT_TIMESTAMP()),
    ('ALT-HERO2', 'CUST-1042', 'TXN-HERO03', 'STRUCTURING', 88.00, 'RULE-STR-001', DATEADD('hour', -24, CURRENT_TIMESTAMP()), 'OPEN', CURRENT_TIMESTAMP()),
    ('ALT-HERO3', 'CUST-1042', 'TXN-HERO05', 'GEO_ANOMALY', 82.00, 'RULE-GEO-001', DATEADD('hour', -12, CURRENT_TIMESTAMP()), 'OPEN', CURRENT_TIMESTAMP()),
    ('ALT-HERO4', 'CUST-1042', 'TXN-HERO01', 'BENEFICIARY_BURST', 78.00, 'RULE-BEN-001', DATEADD('hour', -35, CURRENT_TIMESTAMP()), 'OPEN', CURRENT_TIMESTAMP()),
    ('ALT-HERO5', 'CUST-1042', 'TXN-HERO01', 'VELOCITY_SPIKE', 75.00, 'RULE-VEL-001', DATEADD('hour', -34, CURRENT_TIMESTAMP()), 'OPEN', CURRENT_TIMESTAMP()),
    ('ALT-HERO6', 'CUST-1042', 'TXN-HERO01', 'VALUE_SPIKE', 80.00, 'RULE-VAL-001', DATEADD('hour', -33, CURRENT_TIMESTAMP()), 'OPEN', CURRENT_TIMESTAMP());

-- Hero investigation case
INSERT INTO INVESTIGATION_CASES VALUES
    ('CASE-FG-1042', 'ALT-HERO1', 'CUST-1042', 'ESCALATED', 'CRITICAL',
     'Priya Sharma', CURRENT_DATE(), NULL, NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Hero scenario metadata
INSERT INTO SCENARIO_METADATA VALUES
    ('SCN-I', 'COMBINED', 'CUST-1042', 'ACCT-H1043',
     DATEADD('day', -5, CURRENT_DATE()), CURRENT_DATE(),
     'VELOCITY_SPIKE,STRUCTURING,BENEFICIARY_BURST,GEO_ANOMALY,VALUE_SPIKE', 'CRITICAL',
     'Hero case: ~57L outgoing vs 12L baseline, 5 new beneficiaries, 7 txns in 36hrs, India-UAE-HK, structuring below 10L');
