-- BANKGUARD AI – M4 Audit Tables
-- Schema: BANKGUARD_AUDIT

USE DATABASE BANKGUARD_DB;
USE SCHEMA BANKGUARD_AUDIT;

CREATE OR REPLACE TABLE AI_DECISION_LOG (
    LOG_ID             VARCHAR(40)    NOT NULL DEFAULT UUID_STRING(),
    SESSION_ID         VARCHAR(100),
    CUSTOMER_ID        VARCHAR(20),
    CASE_ID            VARCHAR(20),
    QUERY_TEXT         VARCHAR(4000)  NOT NULL,
    RESPONSE_TEXT      VARCHAR(16000),
    EVIDENCE_REFS      VARIANT        COMMENT 'JSON: signal IDs, transaction IDs, policy citations',
    POLICY_CITATIONS   VARIANT        COMMENT 'JSON array of cited policy sections',
    MODEL_USED         VARCHAR(100),
    TOOL_CALLS         VARIANT        COMMENT 'JSON: tools invoked and their results',
    RESPONSE_STATUS    VARCHAR(20)    DEFAULT 'COMPLETED',
    CREATED_AT         TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_AI_LOG PRIMARY KEY (LOG_ID)
) COMMENT = 'Audit trail for all Cortex Agent interactions.';

CREATE OR REPLACE TABLE INVESTIGATION_FINDINGS (
    FINDING_ID         VARCHAR(40)    NOT NULL DEFAULT UUID_STRING(),
    CASE_ID            VARCHAR(20)    NOT NULL,
    CUSTOMER_ID        VARCHAR(20)    NOT NULL,
    FINDING_TYPE       VARCHAR(50)    NOT NULL,
    FINDING_TITLE      VARCHAR(200)   NOT NULL,
    FINDING_TEXT       VARCHAR(8000)  NOT NULL,
    EVIDENCE_REFS      VARIANT,
    POLICY_CITATIONS   VARIANT,
    SEVERITY           VARCHAR(10),
    ANALYST_REVIEW     VARCHAR(20)    DEFAULT 'PENDING',
    REVIEWER           VARCHAR(50),
    REVIEW_DATE        TIMESTAMP_NTZ,
    REVIEW_NOTES       VARCHAR(2000),
    RULE_VERSION       VARCHAR(20)    DEFAULT 'M2-RISK-V1.0',
    CREATED_AT         TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FINDINGS PRIMARY KEY (FINDING_ID)
) COMMENT = 'AI-generated investigation findings. Require human analyst approval.';
