-- BANKGUARD AI – M2 Risk Evidence & Score Tables
-- Rule Version: M2-RISK-V1.0

USE DATABASE BANKGUARD_DB;
USE SCHEMA BANKGUARD_RISK;

CREATE OR REPLACE TABLE RISK_SIGNAL_EVIDENCE (
    SIGNAL_ID         VARCHAR(40)    NOT NULL,
    CUSTOMER_ID       VARCHAR(20)    NOT NULL,
    ACCOUNT_ID        VARCHAR(20),
    SIGNAL_TYPE       VARCHAR(50)    NOT NULL,
    DETECTED_AT       TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    OBSERVATION_START DATE           NOT NULL,
    OBSERVATION_END   DATE           NOT NULL,
    SEVERITY          VARCHAR(10)    NOT NULL,
    SIGNAL_SCORE      NUMBER(5,2)    NOT NULL,
    EVIDENCE_SUMMARY  VARCHAR(1000)  NOT NULL,
    EVIDENCE_JSON     VARIANT        NOT NULL,
    SOURCE_TABLE      VARCHAR(100)   NOT NULL,
    RULE_VERSION      VARCHAR(20)    NOT NULL DEFAULT 'M2-RISK-V1.0',
    CONSTRAINT PK_SIGNAL_EVIDENCE PRIMARY KEY (SIGNAL_ID)
) COMMENT = 'Detected risk signals with structured evidence.';

CREATE OR REPLACE TABLE CUSTOMER_RISK_SCORE (
    CUSTOMER_ID      VARCHAR(20)    NOT NULL,
    CALCULATION_DATE DATE           NOT NULL,
    RISK_SCORE       NUMBER(5,2)    NOT NULL,
    RISK_CLASS       VARCHAR(10)    NOT NULL,
    SIGNAL_COUNT     NUMBER(3,0)    NOT NULL,
    TOP_SIGNAL       VARCHAR(50),
    SIGNAL_SUMMARY   VARCHAR(2000),
    RULE_VERSION     VARCHAR(20)    NOT NULL DEFAULT 'M2-RISK-V1.0',
    CONSTRAINT PK_RISK_SCORE PRIMARY KEY (CUSTOMER_ID, CALCULATION_DATE)
) COMMENT = 'Customer-level composite risk scores. 0-100 scale.';

-- Classification: 0-24 LOW, 25-49 MEDIUM, 50-74 HIGH, 75-100 CRITICAL
