-- BANKGUARD AI – M3 Regulatory Table DDL
-- Schema: BANKGUARD_REGULATORY
-- All policy content is SYNTHETIC DEMONSTRATION CONTENT.

USE DATABASE BANKGUARD_DB;
USE SCHEMA BANKGUARD_REGULATORY;

CREATE OR REPLACE TABLE POLICIES (
    POLICY_ID          VARCHAR(30)    NOT NULL,
    POLICY_VERSION     VARCHAR(10)    NOT NULL,
    POLICY_TITLE       VARCHAR(200)   NOT NULL,
    POLICY_DOMAIN      VARCHAR(50)    NOT NULL,
    STATUS             VARCHAR(20)    NOT NULL,
    EFFECTIVE_DATE     DATE           NOT NULL,
    SUPERSEDED_DATE    DATE,
    SOURCE_TYPE        VARCHAR(30)    NOT NULL DEFAULT 'SYNTHETIC_DEMO',
    SOURCE_NAME        VARCHAR(100)   NOT NULL DEFAULT 'BANKGUARD AI Synthetic Policy Library',
    OWNER_FUNCTION     VARCHAR(50)    NOT NULL,
    REVIEW_FREQUENCY   VARCHAR(20)    NOT NULL DEFAULT 'ANNUAL',
    CREATED_AT         TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_POLICIES PRIMARY KEY (POLICY_ID, POLICY_VERSION)
) COMMENT = 'SYNTHETIC DEMONSTRATION POLICIES. Not actual legal or regulatory advice.';

CREATE OR REPLACE TABLE POLICY_SECTIONS (
    POLICY_ID          VARCHAR(30)    NOT NULL,
    POLICY_VERSION     VARCHAR(10)    NOT NULL,
    SECTION_ID         VARCHAR(30)    NOT NULL,
    SECTION_NUMBER     VARCHAR(10)    NOT NULL,
    SECTION_TITLE      VARCHAR(200)   NOT NULL,
    SECTION_TEXT        VARCHAR(4000)  NOT NULL,
    RISK_TOPIC         VARCHAR(50)    NOT NULL,
    CONTROL_OBJECTIVE  VARCHAR(500),
    REQUIRED_ACTION    VARCHAR(500),
    EVIDENCE_REQUIREMENT VARCHAR(500),
    ESCALATION_GUIDANCE VARCHAR(500),
    CONSTRAINT PK_SECTIONS PRIMARY KEY (SECTION_ID),
    CONSTRAINT FK_SECTIONS_POLICY FOREIGN KEY (POLICY_ID, POLICY_VERSION)
        REFERENCES POLICIES(POLICY_ID, POLICY_VERSION)
) COMMENT = 'Policy sections chunked for retrieval. SYNTHETIC DEMONSTRATION CONTENT.';

CREATE OR REPLACE TABLE RISK_TOPIC_TAXONOMY (
    TOPIC_CODE   VARCHAR(30)  NOT NULL,
    TOPIC_NAME   VARCHAR(100) NOT NULL,
    DESCRIPTION  VARCHAR(300) NOT NULL,
    CONSTRAINT PK_TOPIC PRIMARY KEY (TOPIC_CODE)
) COMMENT = 'Controlled risk topic taxonomy.';

CREATE OR REPLACE TABLE POLICY_RISK_MAPPING (
    MAPPING_ID     VARCHAR(40)  NOT NULL,
    RISK_SIGNAL    VARCHAR(50)  NOT NULL,
    POLICY_ID      VARCHAR(30)  NOT NULL,
    POLICY_VERSION VARCHAR(10)  NOT NULL,
    SECTION_ID     VARCHAR(30)  NOT NULL,
    RELEVANCE      VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_MAPPING PRIMARY KEY (MAPPING_ID),
    CONSTRAINT FK_MAPPING_SECTION FOREIGN KEY (SECTION_ID)
        REFERENCES POLICY_SECTIONS(SECTION_ID)
) COMMENT = 'Maps M2 risk signals to applicable policy sections.';

CREATE OR REPLACE TABLE POLICY_EVIDENCE_REQUIREMENTS (
    REQUIREMENT_ID       VARCHAR(40)   NOT NULL,
    SECTION_ID           VARCHAR(30)   NOT NULL,
    EVIDENCE_TYPE        VARCHAR(50)   NOT NULL,
    EVIDENCE_DESCRIPTION VARCHAR(500)  NOT NULL,
    SOURCE_TABLE         VARCHAR(100),
    CONSTRAINT PK_EVIDENCE_REQ PRIMARY KEY (REQUIREMENT_ID),
    CONSTRAINT FK_EVREQ_SECTION FOREIGN KEY (SECTION_ID)
        REFERENCES POLICY_SECTIONS(SECTION_ID)
) COMMENT = 'Evidence requirements per policy section.';
