-- BANKGUARD AI – M3 Validation Queries

USE DATABASE BANKGUARD_DB;

-- 1. Every policy has at least one version
SELECT 'Policies without versions' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM (SELECT DISTINCT POLICY_ID FROM BANKGUARD_REGULATORY.POLICIES
      EXCEPT SELECT DISTINCT POLICY_ID FROM BANKGUARD_REGULATORY.POLICY_SECTIONS);

-- 2. No duplicate active versions
SELECT 'Duplicate active versions' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM (SELECT POLICY_ID FROM BANKGUARD_REGULATORY.POLICIES WHERE STATUS='ACTIVE' GROUP BY POLICY_ID HAVING COUNT(*)>1);

-- 3. Superseded policies have superseded_date
SELECT 'Superseded without date' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM BANKGUARD_REGULATORY.POLICIES WHERE STATUS='SUPERSEDED' AND SUPERSEDED_DATE IS NULL;

-- 4. Active policies have sections
SELECT 'Active without sections' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM BANKGUARD_REGULATORY.POLICIES p
WHERE p.STATUS='ACTIVE' AND NOT EXISTS (
    SELECT 1 FROM BANKGUARD_REGULATORY.POLICY_SECTIONS ps
    WHERE ps.POLICY_ID=p.POLICY_ID AND ps.POLICY_VERSION=p.POLICY_VERSION);

-- 5. Every risk signal maps to at least one active policy
SELECT 'Unmapped signals' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM (SELECT DISTINCT SIGNAL_TYPE FROM BANKGUARD_RISK.RISK_SIGNAL_EVIDENCE
      EXCEPT SELECT DISTINCT RISK_SIGNAL FROM BANKGUARD_REGULATORY.POLICY_RISK_MAPPING m
      JOIN BANKGUARD_REGULATORY.POLICIES p ON m.POLICY_ID=p.POLICY_ID AND m.POLICY_VERSION=p.POLICY_VERSION
      WHERE p.STATUS='ACTIVE');

-- 6. Sections have risk topics
SELECT 'Sections without topic' AS CHECK_NAME, COUNT(*) AS VIOLATIONS
FROM BANKGUARD_REGULATORY.POLICY_SECTIONS WHERE RISK_TOPIC IS NULL OR RISK_TOPIC='';

-- 7. Negative policy gate
SELECT * FROM BANKGUARD_REGULATORY.V_NEGATIVE_POLICY_GATE WHERE POLICY_STATUS = 'NO_APPLICABLE_POLICY_FOUND';

-- 8. Hero case policy chain
SELECT SIGNAL_TYPE, POLICY_ID, POLICY_VERSION, SECTION_ID, SECTION_TITLE, RELEVANCE
FROM BANKGUARD_REGULATORY.V_SIGNAL_POLICY_CHAIN
WHERE CUSTOMER_ID = 'CUST-1042'
ORDER BY SIGNAL_TYPE, RELEVANCE;
