-- BANKGUARD AI – M4 Cortex Search Service
-- Creates the search service over regulatory policy documents.

USE DATABASE BANKGUARD_DB;

CREATE OR REPLACE CORTEX SEARCH SERVICE BANKGUARD_REGULATORY.POLICY_SEARCH_SERVICE
    ON SEARCH_TEXT
    PRIMARY KEY (DOCUMENT_ID)
    ATTRIBUTES POLICY_DOMAIN, RISK_TOPIC, STATUS, SOURCE_TYPE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 day'
    COMMENT = 'Cortex Search over synthetic regulatory policy documents.'
AS (
    SELECT DOCUMENT_ID, POLICY_ID, POLICY_VERSION, SECTION_ID,
           TITLE, CONTENT, POLICY_DOMAIN, RISK_TOPIC,
           STATUS, EFFECTIVE_DATE, SOURCE_TYPE, SOURCE_NAME, SEARCH_TEXT
    FROM BANKGUARD_REGULATORY.V_RETRIEVAL_DOCUMENTS
);
